# prometheus.yaml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "dex-nodes"
    static_configs:
      - targets:
          - "localhost:9101"
          - "localhost:9102"
          - "localhost:9103"

  - job_name: "global"
    scheme: https
    tls_config:
      ca_file: "/etc/prometheus/secrets/client_ca.crt"
      cert_file: "/etc/prometheus/secrets/dev_cert.crt"
      key_file: "/etc/prometheus/secrets/dev_key.key"
      # Hinweis: Nur im Dev-Umfeld aktivieren, nicht in Produktion!
      # insecure_skip_verify: true
    static_configs:
      - targets:
          - "deine-node-ip-oder-hostname:9443"

  - job_name: "node"
    static_configs:
      - targets:
          - "deine-node-ip-oder-hostname:9200"
