# my_dex/k8s/helm/templates/configmap.yaml
#
# NEU (Sicherheitsupdate):
#  - Kommentar, dass Passwörter in Klartext (keystore_pass) in Production NICHT empfohlen
#  - Optionale Signatur oder Helm Secrets für das ConfigFile
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dex-config
  labels:
    app: my-dex
data:
  node_config.yaml: |
    node_id: "HelmNode"
    listen_addr: "0.0.0.0:9000"
    metrics_addr: "0.0.0.0:9100"
    jaeger_addr: "jaeger:6831"
    atomic_swap_timeout_sec: {{ .Values.nodeConfig.swapTimeoutSec | default 7200 }}
    crdt_merge_interval_sec: {{ .Values.nodeConfig.crdtMergeIntervalSec | default 10 }}
    log_level: "{{ .Values.nodeConfig.logLevel }}"
    db_path: "/data/dex_db"
    db_max_retries: 3
    db_backoff_sec: 2
    merge_max_retries: 3
    merge_backoff_sec: 1
    use_noise: true
    keystore_path: "keystore.json"
    keystore_pass: "SUPER_SECRET"    # Achtung: Klartextpasswort => in Production besser als Secret
    allowed_node_pubkeys: []
    order_timeout_sec: {{ .Values.nodeConfig.orderTimeoutSec | default 86400 }}
    swap_timeout_sec: {{ .Values.nodeConfig.swapTimeoutSec | default 7200 }}
    num_shards: 4
    partial_fill_min_amount: 0.0001
